### ISSUE TITLE
Problem when accessing RN libraries assets.

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/WooCommerce-Shared#61] opened 2023-07-13 21:50 UTC
# Issue

Recently I found a situation on iOS where a back button **IS NOT** being rendered when running the demo app against the compiled framework but it is rendered when running it against the metro server.

Metro Server | Compiled Framework
---- | ----
<img width="320" alt="local-0" src="https://github.com/woocommerce/WooCommerce-Shared/assets/562080/54803b90-1f7d-4195-9c34-3da99f8bb25d"> | <img width="320" alt="transpiled" src="https://github.com/woocommerce/WooCommerce-Shared/assets/562080/38bb053e-c8a9-473e-972a-342346496f78">

# Possible Cause

After digging into it:

- It seems that RN is using an asset called `back-icon.png` to render that button.
- I can't find that asset in the `WooCommerseShared.xcframework` package.

Could it be that the assets from the RN libraries we use are not being properly included in the `xcframework`, hence not being rendered?

@jkmassel or @mokagio does this makes any sense? Or should I look at a different angle?

**Comment by jkmassel** [comment] 2023-07-17 23:54
> Could it be that the assets from the RN libraries we use are not being properly included in the xcframework, hence not being rendered?

This is a possibility, and I can look into it tomorrow.

@Ecarrion – if you have a branch I can review, that'd help a lot!!

**Comment by Ecarrion** [comment] 2023-07-18 01:01
>  if you have a branch I can review, that'd help a lot!!

@jkmassel sure, the branch `issue/47-support-back-navigation` from [this PR](https://github.com/woocommerce/WooCommerce-Shared/pull/54) has the behaviour described in this issue.

**Comment by jkmassel** [comment] 2023-07-18 21:32
This should be resolved in `add/assets-to-xcframework` – if you were to point SwiftPM at [2b4422a](https://github.com/woocommerce/WooCommerce-Shared/commit/2b4422a3a3f89eb6b30c0daeba0d6c0dc2a31ad7), it should work.

That said, I'm not sure that giving React Native control over the navigation stack is a great approach long-term – if you inspect the view hierarchy, you'll see that it's dropping the RN navigation controller _inside_ the UINavigationController. Unfortunately, using RN as a library (and not basing the whole app on it) has very different considerations, and following along with the tutorials on things like navigation is likely to take you down the wrong road 😞

**Comment by Ecarrion** [comment] 2023-07-19 02:27
Hey @jkmassel,

First of all, thanks for the help! 🙇 

>  I'm not sure that giving React Native control over the navigation stack is a great approach long-term

We are not sure either 😛 

We also thought about having a native module so we can indicate from RN when to push a new controller/view but that also comes with some cons:

- Passing parameters between screens becomes more fragile.
- Increases native development time on both platforms.

Currently, we are just experimenting with what works best for us, so nothing is set on store 😅 

> following along with the tutorials on things like navigation is likely to take you down the wrong road

We have noticed that 🫠, things tend to be more complicated because of the library nature of this experiment, we are finding out things every day!

----

That being said, is the plan to create a PR with those changes so we can finish validating our https://github.com/woocommerce/WooCommerce-Shared/pull/54 experiment? 😁

**Comment by mokagio** [comment] 2023-07-19 04:59
> That being said, is the plan to create a PR with those changes so we can finish validating our https://github.com/woocommerce/WooCommerce-Shared/pull/54 experiment? 😁

I can't speak for @jkmassel , but my summary understanding is that the changes proposed in #54 are good regardless of the approach to navigation that the library and its consumers adopt.

That is, the library should always include the necessary assets, regardless of what we decide to do in terms of navigation.

So, I took the liberty of create #63 to push the work forward just a bit and make it faster to get the changes in if we see fit.

**Comment by Ecarrion** [comment] 2023-07-19 19:22
@jkmassel @mokagio thanks for the work so far, I really appreciate it 🙇 

I feel like we are getting very close, but still, the assets are not being rendered when targeting the `xcframework`  😢 

---- 

I inspected the RN native calls and it seems like the library is trying to load the assets with this path:

```
WooCommerceShared.xcframework/assets/node_modules/@react-navigation/elements/src/assets/back-icon@3x.png
```

But out `xcframework` is contains the assets in `WooCommerceShared.xcframework/Assets.car`

I tried to find a quick way to modify that on the `xcodebuild` params but failed 😞 

However, if I manually paste the assets in that location they do render correctly!

-----

Now, I'm thinking that we could copy the assets manually* in that location as a part of the build script but I'm not sure how fragile this is(especially with new versions of react native) or if there is a better way to do it.

```
* The assets in build/assets have the correct folder structure
```
Do you have any thoughts? 

Thanks in advance!

**Comment by mokagio** [comment] 2023-07-21 08:37
@Ecarrion 

> the assets are not being rendered when targeting the xcframework 😢

What kind of integration are you using to verify this? I'm assuming you are running WooCommerce with the XCFramework embedded there?

I say this because I can see the demo app uses the framework target directly, not the XCFramework.

<img width="945" alt="image" src="https://github.com/woocommerce/WooCommerce-Shared/assets/1218433/5d217e57-87eb-4ff4-b804-8df979d93a98">

I don't know what the development workflow here is, but I wonder if we would benefit from using the XCFramework in the demo app? Granted, the loop would be very slow because we'd need to build the XCFramework every time, which takes time. On the other hand, it would give us a setup that is closer to the real way the library is integrated. 🤔 

The whole reason I'm asking this, by the way, is because I wanted to reproduce the issue on my end. For that purpose, I only need to know the approach you're currently using. 😄 Is there a branch in WooCommerce I can point to?

**Comment by Ecarrion** [comment] 2023-07-21 13:14
Hey @mokagio, yes! You can use the issue/47-support-back-navigation branch.

I'm testing with the demo app and embedded framework, but I have also validated that wcios + xcframework has the same behavior. 

I think that the embedded framework should have the same contents as the resulting xcframework, so it should not be necessary to run the demo app against the xcframework and slow development times 😀 

Let me know, how else I can help!

**Comment by Ecarrion** [comment] 2023-07-25 19:43
@mokagio I just merged `trunk` into `issue/47-support-back-navigation` and now you can [set the store credentials](https://github.com/woocommerce/WooCommerce-Shared#credentials) on the `env` file.

Hopefully, this will let you run the demo app easier. :-) 

I do want to ask you if you are planning to work on this soon or if w should look for alternatives. 😅 
This is our last blocker to release the experiment into production. 

cc @wzieba

**Comment by mokagio** [comment] 2023-07-26 06:23
@Ecarrion After an afternoon of exploration, I still have no idea how to make those assets available. However, I found a workaround that at least shows _something_ there:

<img alt="image" src="https://github.com/woocommerce/WooCommerce-Shared/assets/1218433/7fdaee57-278a-4f31-b5ec-74f7415d71c2" width=300/>


See #67

**Comment by Ecarrion** [comment] 2023-07-26 21:44
@mokagio thanks a lot for the workaround! I think I may have found a solution to the asset problem. Please take a look at #70

**Closed as completed** 2023-07-27 12:23 UTC
